export const categoryConstants = {
  GET_ALL_REQUEST: "GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "GET_ALL_FAILURE",
};

export const authConstants = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
};

export const productConstants = {
  GET_ALL_DATA_REQUEST: "GET_ALL_DATA_REQUEST",
  GET_ALL_DATA_SUCCESS: "GET_ALL_DATA_SUCCESS",
  GET_ALL_DATA_FAILURE: "GET_ALL_DATA_FAILURE",
  GET_SLUG_SUCCESS: "GET_SLUG_SUCCESS",
};

export const cartConstants = {
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_REQUEST: "GET_CART_REQUEST",
  REMOVE_CART_SUCCESS: "REMOVE_CART_SUCCESS",
  ADD_PRODUCT_BASKET: "ADD_PRODUCT_BASKET",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  CLEAR_PRODUCT: "CLEAR_PRODUCT",
};
